version: '3'

services:
  php:
    build: ./docker/php
    tty: true # -t option in docker
    stdin_open: true # -i option in docker
    hostname: idrolab_datapool
    volumes:
      - ./:/var/www/app
      - ./docker/data/composer:/home/utente/.composer
