version: '3'

services:
#  nginx:
#    image: matiux/debian-nginx:symfony
#    ports:
#      - '8080:80'
#    depends_on:
#      - php
#    volumes:
#      - ./docker/logs/nginx/:/var/log/nginx
#      - ./:/var/www/app
  php:
    build: ./docker/php
    tty: true # -t option in docker
    stdin_open: true # -i option in docker
    hostname: idrolab_datapool
    volumes:
      - ./:/var/www/app
      - ./docker/data/composer:/home/utente/.composer
#      - ./docker/data/composer/cache:/home/utente/.composer/cache
    environment:
      - APP_ENV=${APP_ENV}
#  servicedb:
#    image: mariadb
#    #restart: always
#    volumes:
#      - ./docker/data/db:/var/lib/mysql
#    environment:
#      - MYSQL_ROOT_PASSWORD=${DOCKER_MYSQL_ROOT_PASSWORD}
#      # - MARIADB_DATABASE=app_db
#      # - MARIADB_USER=app_db_user
#      # - MARIADB_PASSWORD=
#    #command: mysqld --sql_mode="" #Per mysql
#    ports:
#      - '3307:3306'
#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    ports:
#      - "8081:80"
#    depends_on:
#      - servicedb
#    environment:
#      - PMA_HOST=servicedb
  # memcached:
  #   image: memcached:latest
  #   volumes:
  #     - ./docker/data/memcached:/var/lib/memcached
#  redis_db:
#    image: redis:alpine
#    #command: redis-server --requirepass redis
#    ports: ["6379"]
